package com.pedroeu.ficha

import com.pedroeu.ficha.data.content.FeatData
import com.pedroeu.ficha.data.content.MagicItemData
import com.pedroeu.ficha.data.content.PerUseChoiceData
import com.pedroeu.ficha.data.content.SpeciesData
import com.pedroeu.ficha.data.content.SpellData
import com.pedroeu.ficha.data.content.SubclassData
import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * What the books state, checked against what the app says — without a network.
 *
 * A sweep that needs the reference site is a sweep that runs when somebody remembers to run
 * it, which in practice is after a player has already found the mistake. So the part of the
 * reference that can be checked mechanically — the numbers each entry states — is frozen into
 * `reference-digest.json` and checked here, in the same half-second as every other test.
 *
 * Numbers only, deliberately. The app paraphrases and reorders prose, and a test that demanded
 * identical wording would fail constantly for no benefit and be switched off inside a week. A
 * die, a distance, a duration, a save DC or a price is where a mistake costs a player something
 * at the table, and none of those has a second correct spelling.
 *
 * The digest is regenerated by the scraper when the books change; a number that disappears from
 * the app between now and then fails the build with the entry's name and the missing figure.
 */
class ReferenceParityTest {

    private val digest: JsonObject by lazy {
        val file = listOf(
            File("src/test/resources/reference-digest.json"),
            File("app/src/test/resources/reference-digest.json"),
        ).first { it.isFile }
        Json.parseToJsonElement(file.readText()).jsonObject
    }

    /** What the app says about one entry, fields and prose together. */
    private fun appText(): Map<String, Map<String, String>> = mapOf(
        "spells" to SpellData.ALL.associate {
            it.name to listOf(
                it.castingTime, it.range, it.components, it.duration, it.description,
            ).joinToString(" ")
        },
        "feats" to FeatData.ALL.associate { it.name to it.description },
        "species" to SpeciesData.ALL.associate { species ->
            species.name to listOf(
                species.summary,
                "${species.speed} ft",
                "${species.darkvisionRange} ft",
                // A trait's options are its content too: the Aasimar's Celestial Revelation
                // is three transformations, and the trait that introduces them states none of
                // their numbers.
                species.traits.joinToString(" ") { trait ->
                    trait.name + " " + trait.description + " " +
                        trait.choices.joinToString(" ") { choice ->
                            choice.options.joinToString(" ") { "${it.name} ${it.description}" }
                        }
                },
                species.lineageOptions.joinToString(" ") { "${it.name} ${it.description}" },
                // And what it decides at the moment of use. The Aasimar's three revelations
                // are a per-use choice, not a trait, and every number they state — the
                // 10-foot radius, the DC — is stated only there.
                PerUseChoiceData.ALL
                    .filter { it.speciesId == species.id }
                    .joinToString(" ") { perUse ->
                        perUse.options.joinToString(" ") { "${it.name} ${it.description}" }
                    },
            ).joinToString(" ")
        },
        // A subclass's options are its content too: the Arcane Archer's shots and the
        // Battle Master's manoeuvres are where most of its numbers live, and reading only the
        // feature that introduces them reports every one of those numbers as lost.
        "subclasses" to SubclassData.ALL.associate { subclass ->
            subclass.name to subclass.features.joinToString(" ") { feature ->
                feature.name + " " + feature.description + " " +
                    feature.choices.joinToString(" ") { choice ->
                        choice.options.joinToString(" ") { "${it.name} ${it.description}" }
                    }
            }
        },
        "magicItems" to MagicItemData.ALL.associate { it.name to it.description },
    )

    /** A number as the digest writes it: no spaces, feet spelled one way. */
    private fun numbersIn(text: String): Set<String> =
        NUMBER.findAll(text)
            .map {
                it.value.lowercase().replace(Regex("\\s+"), "")
                    .replace("foot", "ft").replace("feet", "ft")
            }
            .toSet()

    @Test
    fun `every number the books state is still somewhere in the app`() {
        val app = appText()
        val missing = mutableListOf<String>()

        digest.forEach { (domain, entriesJson) ->
            val ours = app[domain] ?: return@forEach
            entriesJson.jsonObject.forEach { (name, entry) ->
                val text = ours[name] ?: return@forEach
                val have = numbersIn(text)
                val lost = entry.jsonObject.getValue("numbers").jsonArray
                    .map { it.jsonPrimitive.content }
                    .filterNot { it in have }
                    .filterNot { "$domain|$name|$it" in ALLOWED }
                if (lost.isNotEmpty()) {
                    missing += "  $domain / $name is missing ${lost.take(6)}"
                }
            }
        }

        assertTrue(
            "${missing.size} entries have lost a number the books state:\n" +
                missing.take(40).joinToString("\n") +
                "\n\nIf the books changed, regenerate reference-digest.json. If the app is " +
                "right and the reference is quoting something the app keeps elsewhere, add " +
                "the entry to ALLOWED with the reason.",
            missing.isEmpty(),
        )
    }

    private companion object {
        /**
         * Numbers worth checking: dice, distances, times, DCs, prices.
         *
         * A bare small integer is noise — it appears in cross-references and page furniture —
         * so a number has to carry a unit or be a die to count. The same expression the
         * scraper uses, so the two sides cannot drift apart.
         */
        val NUMBER = Regex(
            "\\b(\\d+d\\d+(?:\\s*\\+\\s*\\d+)?" +
                "|\\d+\\s*(?:feet|foot|ft|mile|miles)" +
                "|\\d+\\s*(?:hour|hours|minute|minutes|day|days|round|rounds)" +
                "|dc\\s*\\d+" +
                "|\\+\\s*\\d+\\b" +
                "|\\d+\\s*gp|\\d+\\s*sp|\\d+\\s*cp)",
            RegexOption.IGNORE_CASE,
        )

        /**
         * Figures the reference states and the app keeps somewhere this test cannot see.
         *
         * Each needs a reason. An empty exception is how a check like this rots: one
         * unexplained entry becomes twenty, and then the test is passing because nobody is
         * looking rather than because the app is right.
         */
        val ALLOWED: Set<String> = buildSet {
            // A summoned creature's numbers live on its stat block, which is where the sheet
            // reads them and where a player looks; SummonTest is what fails the build for a
            // summoning spell with no creature behind it.
            val summons = listOf("Battle Familiar", "Summon Plant", "Summon Dinosaur")
            val creatureNumbers = listOf(
                "1d4", "3d4", "1d8+3", "1d10", "1d10+3", "1d10+5", "2d10+5",
                "5ft", "10ft", "30ft", "40ft",
            )
            summons.forEach { spell ->
                creatureNumbers.forEach { add("spells|$spell|$it") }
            }
        }
    }
}
